
// Configurations EmailJS
export const EMAILJS_CONFIG = {
  // Remplacer ces valeurs par vos identifiants réels EmailJS
  PUBLIC_KEY: "VOTRE_CLE_PUBLIQUE_EMAILJS",
  SERVICE_ID: "VOTRE_SERVICE_ID",
  TEMPLATES: {
    CONTACT: "VOTRE_TEMPLATE_CONTACT",
    PASSWORD_RESET: "VOTRE_TEMPLATE_PASSWORD_RESET",
    WELCOME: "VOTRE_TEMPLATE_BIENVENUE",
    COURSE_REMINDER: "VOTRE_TEMPLATE_RAPPEL_COURS",
    ACHIEVEMENT: "VOTRE_TEMPLATE_ACCOMPLISSEMENT"
  }
};
